# Generated by Django 4.1.5 on 2023-01-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='final.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgFuelConsumptionPer100Km', models.FloatField()),
                ('total_score', models.FloatField()),
                ('anticipation', models.FloatField()),
                ('braking', models.FloatField()),
                ('coasting', models.FloatField()),
                ('speedAdaption', models.FloatField()),
                ('standstill', models.FloatField()),
                ('idling', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.user')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclesInFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('Fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.fleet')),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.vehicle')),
            ],
        ),
    ]
