# Generated by Django 4.1.5 on 2023-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_fleet_vehicle_vehiclesinfleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
