# Generated by Django 4.1.5 on 2023-01-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_vehicle_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
