# Generated by Django 4.1.5 on 2023-01-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_alter_vehicle_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='final.vehicle')),
            ],
        ),
    ]
