# Generated by Django 4.1.5 on 2023-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_remove_vehicle_anticipation_remove_vehicle_braking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesinfleet',
            name='amount',
        ),
        migrations.AddField(
            model_name='fleet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
