# Generated by Django 4.1.5 on 2023-02-03 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0012_alter_vehicle_last_data_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_data_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 1, 23, 56, 727156)),
        ),
    ]
