# Generated by Django 4.1.5 on 2023-02-03 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0014_vehicle_user_id_alter_vehicle_last_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_data_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 2, 28, 59, 39353)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final.user'),
        ),
    ]
