# Generated by Django 4.1.5 on 2023-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_remove_vehicle_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_data_upload',
            field=models.DateTimeField(),
        ),
    ]
