# Generated by Django 4.1.5 on 2023-02-03 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0017_alter_vehicle_last_data_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='first_data_upload',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 17, 15, 8, 800810)),
        ),
    ]
