# Generated by Django 4.1.5 on 2023-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0018_vehicle_first_data_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='distance_traveled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='first_data_upload',
            field=models.DateTimeField(),
        ),
    ]
