# Generated by Django 4.1.5 on 2023-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0019_vehicle_distance_traveled_vehicle_fuel_consumed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='average_fuel_consumption_from_update',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='distance_traveled',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_consumed',
            field=models.IntegerField(),
        ),
    ]
