# Generated by Django 4.1.5 on 2023-02-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0021_alter_vehicle_average_fuel_consumption_from_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='days_from_update',
            field=models.IntegerField(default=0),
        ),
    ]
