# Generated by Django 4.1.5 on 2023-02-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0027_rename_user_users_alter_fleet_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
