# Generated by Django 4.1.5 on 2023-02-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0028_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('when', models.DateTimeField()),
            ],
        ),
    ]
