# Generated by Django 4.1.5 on 2023-02-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0029_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
