# Generated by Django 4.1.5 on 2023-02-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0030_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='final.vehicle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
