# Generated by Django 4.1.5 on 2023-02-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0032_alter_event_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='fuel_per100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='milage',
            field=models.IntegerField(default=0),
        ),
    ]
