# Generated by Django 4.1.5 on 2023-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0033_event_fuel_event_fuel_per100_event_milage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='fuel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='fuel_per100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='milage',
            field=models.IntegerField(),
        ),
    ]
